package:
  name: pennies
  version: '0.2.0'

source:
  git_url: https://github.com/caseyclements/pennies
  git_rev: master

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - scipy
    - multipledispatch
    - matplotlib

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - pennies
  commands:
    - pytest -v

about:
  home: https://github.com/caseyclements/pennies
  license: BSD
  license_file: LICENSE
  summary: pythonic quantitative finance library for pricing and risk
